# Generated by Django 5.2.7 on 2025-10-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_turf_aeminities_turf_contact_number_turf_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='aeminities',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='turf',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='turf',
            name='end_time',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turf',
            name='start_time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
