# Generated by Django 5.2.7 on 2025-10-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_turf_aeminities_alter_turf_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='contact_number',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
