# Generated by Django 5.2.7 on 2025-10-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_turf_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='aeminities',
        ),
        migrations.AddField(
            model_name='turf',
            name='amenities',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='turf',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
