# Generated by Django 5.2.7 on 2025-10-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_turf_aeminities_turf_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
