# Generated by Django 5.2.7 on 2025-10-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_turf_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='sport',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='turf',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
