# Generated by Django 5.2.7 on 2025-11-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
